### ISSUE TITLE
Unable to start UDP/TCP

### ISSUE THREAD

**Issue by AdrianoW** [godaddy/Thespian#1]
I am unable to use the TCP or UDP system.

My call is 
```
asys = ActorSystem("multiprocTCPBase", capabilities={"Admin Address": 5001})
```
The error is:

```
 .... lib/python2.7/site-packages/thespian/system/systemBase.py", line 76, in __init__
 'not a valid or useable ActorSystem Admin')
thespian.actors.InvalidActorAddress: ActorAddr-(TCP|192.168.100.9:1900) is not a valid or useable ActorSystem Admin
```

I have tried many different ports and none worked out. I am using a Mac OSX Yosemite.

Thanks

**Comment by kwquick** [comment]
Hi Adriano,


I think the problem is that you want to specify "Admin Port" instead of "Admin Address" in your capabilities if you are using the multiprocTCPBase (4 multiprocTCPBase<http://godaddy.github.io/Thespian/doc/using.html#sec-8-4>) or the multiprocUDPBase.  The "Admin Address" is only used with the multiprocQueueBase.


Regards,

  Kevin


________________________________

**Comment by AdrianoW** [comment]
Hi Kevin

Actually, that was a mix of 2 different tries. I had tried the Admin port
before, and it did not worked as well.

I have changed to
asys = ActorSystem("multiprocTCPBase", capabilities={"Admin Port": 5001})
or
asys = ActorSystem("multiprocTCPBase")

and the error is:

> ... site-packages/thespian/system/multiprocCommon.py", line 69, in
> _startAdmin
>     raise InvalidActorAddress(adminAddr, 'not a valid ActorSystem admin')
> thespian.actors.InvalidActorAddress: ActorAddr-(TCP|192.168.100.9:5001)
> is not a valid ActorSystem admin


When using multiprocQueueBase:

site-packages/thespian/system/multiprocCommon.py", line 69, in _startAdmin
>     raise InvalidActorAddress(adminAddr, 'not a valid ActorSystem admin')
> thespian.actors.InvalidActorAddress: ActorAddr-Q.ThespianQ is not a valid
> ActorSystem admin



Thanks for the help

Adriano

2015-10-13 20:54 GMT-03:00 Kevin Quick <notifications@github.com>:

**Comment by kwquick** [comment]
Adriano,

Interesting.  I'm not exactly sure what is happening (I've just validated thespian locally on OS/X Yosemite 10.10.5 so it should not be a Mac issue), but I'd like to investigate a few things.  First, for your background, the "multiproc*" system bases will start up a separate process which acts as the admin for that Actor System.  This admin will persist until explictly shutdown.  The `ActorSystem()` calls you are using above will create this process if it does not currently exist and then try to verify it by connecting to it and performing an initialization handshake.  The errors you are seeing typically indicate a failure in this startup process: the port you specify is not an Actor System admin, a firewall is blocking access to that port, it is unable to send a packet to that port and receive a response, or the response is not the expected handshake response.

You can look for a running admin on your port 5001 via:

    $ lsof -i :5001

which will show any processes attached to that port.  If you do have processes attached, you may want to either choose a different port or kill those processes to try a full initialization.

If you want to use the "multiprocQueueBase", I would recommend starting with no capabilities specification for initial testing.

Here's an example I just ran.  First, I created `foo.py` with the following contents:

    from thespian.actors import *
    class Foo(Actor):
        def receiveMessage(self, message, sender):
            self.send(sender, "got: " + str(message))

Then I manually ran this actor:

    $ python
    >>> from foo import Foo
    >>> from thespian.actors import *
    >>> asys = ActorSystem('multiprocQueueBase')
    >>> foo = asys.createActor(Foo)
    >>> asys.ask(foo, 'req1', 1)
    'got: req1'
    >>> asys.shutdown()
    >>>
    >>>
    >>> asys = ActorSystem('multiprocTCPBase', capabilities={'Admin Port': 5001})
    --repeat above---

Hopefully the above provides enough information to help you get this resolved.  Please do let me know whether it does or not, and if not I will be happy to help further debug this issue with you.

Regards,
  Kevin

**Comment by kwquick** [comment]
Adriano,

Any luck?

-Kevin

**Comment by AdrianoW** [comment]
Hi Kevin,

sorry for not contacting earlier. Had some work do deliver.

I did some tests and these are the observations:

   - When the computer has just started, the system works.
   - When shutting down the system through the API (.shutdown()), it keeps
   running.
   - After a system is initiated, I am unable to start the queue or the
   UDP/TCP, even if I kill the process in the background.
   - If I kill a process identified by lsof -i :5001 and run the python
   script again, it fails but the process appears again when running lsof -i
   :5001

Could that be something related to the fork in the process used to create
the background agent system. If I am not mistaken, I had a problem with
that once. I had to use the shell to launch the python script in background
as the forking strategy did not work out.

If you need me to do more tests, just let me know. I am interested in doing
a Machine Learning application using actors and using python would be
faster for me.



2015-10-17 1:00 GMT-03:00 Kevin Quick <notifications@github.com>:

**Comment by kwquick** [comment]
Adriano,

Thank you for the detailed information.  Unfortunately, I am unable to reproduce the behavior you are seeing.  I'm using OS X Yosemite 10.10.5, python 2.7, and thespian 2.3.0.  I can run the following test program repeatedly and a `ps -eafw | grep -i [p]ython` between runs shows no output, and neither does `lsof -i :5001`.  Can you please try this test program locally to see if your results are similar or if you still encounter problems?

```python
from thespian.actors import *

class Foo(Actor):
    def receiveMessage(self, msg, sender):
        self.send(sender, "got: " + str(msg))

asys = ActorSystem('multiprocTCPBase', capabilities={'Admin Port': 5001})
foo = asys.createActor(Foo)
print(asys.ask(foo, 'what', 1))
asys.shutdown()
```

-Kevin

**Comment by AdrianoW** [comment]
So Kevin

I've found the root problem

The problem is that I am trying to use Flaskio with thespian. The idea was
to create a web server that would use actors to solve the requests and
communicate through websockets.

The actors would be responsible for, via websocket, answer the client with
the request demanded.

The thing is that at the beginning of the code, I am calling

from gevent import monkey
> monkey.patch_all()


The patch_all() changes the functions to work with gevent and that is
somehow affecting the behavior of thespian. When doing that, Thespian hangs
and I need to kill it through prompt.

So, if I don"t use the monkey_patch, thespian works fine.




2015-10-19 1:16 GMT-02:00 Kevin Quick <notifications@github.com>:

**Comment by kwquick** [comment]
Adriano,

Thanks for the followup, and I'm glad you aren't stuck any longer.  The monkey patching implemented by gevent is clearly interfering with the documented functionality of the standard libraries used in Thespian; I'll add a warning to this effect in the Thespian documentation.

Regarding your overall design, please feel free to contact me via github (or directly at godaddy.com in care of kquick) to explore options: I'd love to know more about your overall design to understand how thespian could be used or perhaps enhanced to facilitate the functionality you are trying to achieve.

Regards,
  Kevin
