### ISSUE TITLE
Based on earlier Thespian library

### ISSUE THREAD

**Issue by BruceEckel** [godaddy/Thespian#15]
I found this: http://pythonhackers.com/p/DrewEaster/thespian
But didn't see any mention of the project in your readme. If this is based on his work, it should say so. If not, it should say that so users don't get confused like I did.

**Comment by kwquick** [comment]
The two projects are unrelated, and I will update the docs to clarify that.  I was unaware of the reference above; thank you for bringing it to my attention. 

(Oddly, it's reported on "pythonhackers.com", but it's a scala project built on top of akka.)

**Comment by BruceEckel** [comment]
Yeah, that's what confused me.


-- Bruce Eckel
www.MindviewInc.com <http://www.mindviewinc.com/>
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com <http://www.ScalaSummit.com>

**Comment by kwquick** [comment]
The documentation at http://thespianpy.com/index.html#outline-container-sec-3 has been updated to distinguish this Thespian against other efforts.
