### ISSUE TITLE
Actor Not Shutting Down

### ISSUE THREAD

**Issue by kevincolyar** [godaddy/Thespian#19]
I have an actor I'm using to do processing on a time interval using:

```
class Timer(Actor):
    def receiveMessage(self, msg, sender):
        if isinstance(msg, WakeupMessage):

            if not getattr(self, 'time_stepper', None):
                self.time_stepper = seconds_time_stepper(init_now())

            if not getattr(self, 'scheduler', None):
                self.scheduler = self.createActor(Scheduler)

            t = next(self.time_stepper)
            logging.info('Woke up: {0}'.format(t))
            self.send(self.scheduler, t)

            self.wakeupAfter(timedelta(seconds=.1))
```

However, when I shutdown the ActorSystem, this actor does not get killed.  I'm wonder if I'm generating too many messages and the `ActorSystem().shutdown()` is just timing out waiting for them to complete and gives up trying to kill that actor?

**Comment by kwquick** [comment]
There's nothing I see below that looks like it would prevent a shutdown.  The ActorSystem will wait for a while for Actors to shutdown, but it will eventually timeout and shutdown with a warning if the Actors do not confirm their exit.

Pending wait messages should not prevent a shutdown, and while the actor's shutdown message is queued with other messages and could therefore be delayed by a busy environment, the 10 msgs/sec indicated by your code and the non-blocking processing of messages in your receiveMessage does not sound high enough to impact the shutdown process.
