### ISSUE TITLE
Add cause to PoisonMessage

### ISSUE THREAD

**Issue by danielmitterdorfer** [godaddy/Thespian#22]
Currently, when an uncaught exception occurs in an actor, Thespian sends a `PoisonMessage` to the sender. However, `PoisonMessage` only contains the original message. It would be nice, if we could also get the original exception e.g. as a `cause` property on `PoisonMessage`.

**Comment by kwquick** [comment]
Added in https://github.com/godaddy/Thespian/releases/tag/thespian-3.4.0
