### ISSUE TITLE
Include relevant package docs in Python distribution

### ISSUE THREAD

**Issue by jcmcken** [godaddy/Thespian#25]
Currently things like the license, contributors doc, and README aren't included in the source distribution on PyPI. People installing from this location have to pull in the license manually, and OS packagers would need to do the same for the rest of the docs.

**Comment by kwquick** [comment]
Thanks for the heads-up!  I'll get this corrected shortly.

________________________________

**Comment by jcmcken** [comment]
Thanks for the quick reply!

**Comment by kwquick** [comment]
Fixed in https://github.com/godaddy/Thespian/releases/tag/thespian-3.4.0
