### ISSUE TITLE
multiprocTCPBase Message Send Queuing?

### ISSUE THREAD

**Issue by kwokhongwong** [godaddy/Thespian#26]
Hi

First off thanks so much for creating a great library.

I have implemented an actor which is sending messages to another actor (multiprocTCPBase) every 10-15 secs.

I've noticed that the 1st message is always sent okay, immediately. But the subsequent messages appear to always queue (and never send).

In particular, in system.systemCommon.py, class systemCommonBase in method _send_intent(self, intent) - the 1st message send satisfies

self._finalTransmitPending.set_last_intent(
                self._sCBStats,
                intent.targetAddr,
                sendAddr,
                intent)

and so appears to send immediately.

Subsequent messages don't satify this (i.e. False is returned) and so appear to be queued.

I've tried to play with the settings in hysteresis.py without success.

I would also add that the message send is triggered by a Wakeup message, sent every 0.5 secs with the data consume from a deque populated by a thread running in the same process (thre thread populates the queue and sleeps for around 15 secs after successfully placing data on the queue).

Could you please provide some guidance on what I can do to ensure the messages do not queue up and are sent in a timely manner?

Apologies if I have overlooked the obvious.

Thanks in advance, Hong...

**Comment by kwokhongwong** [comment]
Hi Again

I've just seen that this issue disappears if I increase the Wakeup interval e.g. to around 2 seconds. The prior setting I had was in fact 0.1 secs (not the 0.5 secs previously indicated).

Hong...

**Comment by kwquick** [comment]
Hi Hong,

I'm glad you are finding Thespian useful, but it does sound like you are seeing something unexpected.

The set_last_intent call above is internally determining if it can send the new message or if the previous message is still being sent.  Normally a message send should happen very quickly.  There is some rate limiting applied by the RateThrottle in that same file, but it should be allowing a much higher rate than one message every 2 seconds; the hysteresis functionality is only used for system messages between convention admins and should not be impacting your test case.

I am concerned that perhaps the receiving actor is doing something that prevents it from interacting properly with the sending Actor.  Can you provide any more information about what the receiver is doing, or alternatively provide a simple test case that reproduces your problem?

-Kevin

**Comment by kwokhongwong** [comment]
Thanks Kevin for the quick response. I'll take another look over and will try to reproduce with a standalone test for you. Hong...

**Comment by kwquick** [comment]
Hi Hong,

Just checking to see if you had a chance to look into this issue and if it's still a problem or if this issue should be closed.

-Kevin

**Comment by kwquick** [comment]
Closing this issue for now.  Please feel free to re-open or create another issue if you are still having trouble.
