### ISSUE TITLE
Troupe Member Initialization

### ISSUE THREAD

**Issue by kevincolyar** [godaddy/Thespian#27]
I'm wanting to use an actor that persists records to a database in troupe configuration but can't come up with a way to initialize the actor with its configuration settings.

Right now I send it a Settings message type when it is first created and it configures itself based on the message.  However, if I set up a troupe, that Settings message will only be send to one actor.

Ideas?  I prefer not to have a global "configuration" that is imported my actors.

**Comment by kwquick** [comment]
Hi Kevin,

We handled this by inverting the initialization process:
   1. Create a "settings" actor with a globalName to hold all the settings.
   2. Each troupe member asks the settings actor for settings if it doesn't already have them.

You will need to use the 3.5.0 or later troupe definition, which allows the troupe member to indicate that it is "busy".  Something like the following:

```
@troupe()
class Worker(ActorTypeDispatcher):
    def receiveMsg_Work(self, message, sender):
        if not hasattr(self, 'settings'):
            self.troupe_work_in_progress = message
            self.send(self.createActor('settings', globalName='SettingsActor'), 'get settings'))
            return
        self.troupe_work_in_progress = False
        ...do work with self.settings...

    def receiveMsg_Settings(self, settings_message, sender)
        self.settings = message
        if self.troupe_work_in_progress:
            self.send(self.myAddress, self.troupe_work_in_progress)    
```

This lets each troupe worker get the settings from the SettingsActor singleton when the worker is first started.

-Kevin

**Comment by kwquick** [comment]
A better update to the above is to allow multiple pending messages to be saved waiting for the settings:

```
@troupe()
class Worker(ActorTypeDispatcher):
    def receiveMsg_Work(self, message, sender):
        if not hasattr(self, 'settings'):
            self.troupe_work_in_progress = getattr(self, 'troup_work_in_progress', list()).append(message)
            self.send(self.createActor('settings', globalName='SettingsActor'), 'get settings'))
            return
        ...do work with self.settings...

    def receiveMsg_Settings(self, settings_message, sender)
        self.settings = message
        for work in self.troupe_work_in_progress:
            self.send(self.myAddress, work)
```

Saving multiple messages shouldn't be necessary for a troupe because only one work item should be delivered to the troupe member at a time, but by using the list to save all messages it means that this implementation works in or out of a troupe configuration (e.g. you could comment out or remove the `@troupe()` line and it would still work just fine).

**Comment by kquick** [comment]
Hi Kevin,

I saw that you closed this issue.  I'm putting together a set of "recipes" for using Thespian in different configurations and had planned to add the above information, but I'm curious to know if it was helpful or if you solved this a different way?

Regards,
  Kevin

**Comment by kevincolyar** [comment]
Yes, very helpful, thanks.  I didn't implement it exactly the same way but did use a global settings actor for my troupe.
