### ISSUE TITLE
Logging example?

### ISSUE THREAD

**Issue by pjz** [godaddy/Thespian#3]
Would it be asking too much to document how logging in an Actor should be done?  and where it goes?  Adding logging to the 'In Depth' example, perhaps?

**Comment by kwquick** [comment]
Great suggestion, thank you.

The "In Depth" documentation now contains much more information on using logging with Thespian, and there is now an `examples` directory in the github source code.

Please let me know if this information helps or if there are further updates needed to clarify the logging.

Thanks,
  Kevin

**Comment by pjz** [comment]
Much appreciated!  I should certainly be able to figure out how it works now.
