### ISSUE TITLE
duplicated log messages

### ISSUE THREAD

**Issue by samlesu** [godaddy/Thespian#31]
We updated Thespian from 3.4.0 to 3.6.0 and we notice that all the logs emitted by an Actor are duplicated using the Python default formatting (and not the logs emitted by the main thread).

So the output looks like this for instance:
> 2017-01-12 11:42:35,787 - sandman.actors.actor:41[29] - INFO - Creating actor `Client`
> INFO:sandman.actors.actor:Creating actor `Client`

We are using the **multiprocTCPBase** system base. I'm manually configuring my local loggers and setting up the thespian loggers using the configuration provided in the documentation.

Are we doing something wrong?

**Comment by kwquick** [comment]
Do you have `propagate = True` and multiple loggers potentially handling the message?  If you could share your logging configuration I could see if this is something I could reproduce.

**Comment by samlesu** [comment]
Thanks for your quick reply, adding `propagate = True` on my package logger solve it.
