### ISSUE TITLE
cPickle option?

### ISSUE THREAD

**Issue by kwadl** [godaddy/Thespian#34]
Getting along very well with Thespian, thanks again for a great project.

One possible enhancement that would make a significant performance difference to our use case is the ability to opt for cPickle for the UDP and TCP transports. It seems this would be entirely compatible with the way the transports are serializing messages, and shouldn't break anything?

**Comment by kwquick** [comment]
I'm glad Thespian is working out well for you.  Using cPickle for Python versions prior to 3.1 is great idea, thank you.  I will try to get this implemented soon.

**Comment by kwquick** [comment]
This has been added in the 3.6.2 release: https://github.com/godaddy/Thespian/releases/tag/thespian-3.6.2.
