### ISSUE TITLE
Actor wakeup

### ISSUE THREAD

**Issue by dkhan11** [godaddy/Thespian#38]
Hi again,

I'm trying to use the wakeupAfter function with no real success. It works but I might just not understand how it supposed to work...
Example:
class MyActor(Actor):

    def receiveMessage(self, message, sender):
        self.wakeupAfter(timedelta(seconds=0.5))
        
hello = ActorSystem().createActor(MyActor)
ActorSystem().ask(hello, message, 1)

Shouldn't this code just run in a loop forever?  I manage to receive the WakupMessage but only if I specify a high timeout for the 'ask', like this:
ActorSystem().ask(hello, message, 10)

What is the right approach for starting an actor and just let it run in a loop without waiting forever for responses?  what is the right approach for just starting an actor and let it run forever?

Thanks for the help.
DD.

**Comment by dkhan11** [comment]
I have tried to just send the message from the actor, just like you did in your examples:
self.send(self.myAddress, WakeupMessage(timedelta(seconds=2)))

It works but for some reason the delayed period is ignored and it just fires rapidly instead of the 2 seconds delay.
Is this the right way to do so?

Thanks,
DD.

**Comment by davinellulinvega** [comment]
Hello,

Try to simply do something like:
```
hello = ActorSystem().createActor(MyActor)
ActorSystem().tell(hello, None)  # None is used in place of a real message here
```
With the implementation of your `MyActor` class as it is, the first message sent by the ActorSystem will be received **immediately** by `hello` and trigger the loop. Subsequent messages should be of type `WakeupMessage` and trigger further `wakeup` calls.
Hence, implementing the kind of **forever** loop you are asking for.

Sincerely.

**Comment by dkhan11** [comment]
Got it, thanks! I will use it.

**Comment by kwquick** [comment]
Thank you @davinellulinvega for providing assistance on this while I was out travelling!

@dkhan11, please feel free to post (either here or on the thespian.py grouplist) if you encounter any additional troubles.

Regards,
  Kevin
