### ISSUE TITLE
Child actor not exiting correctly

### ISSUE THREAD

**Issue by davinellulinvega** [godaddy/Thespian#40]
Hello,

For the last few days I have been able to run a game I created and implemented with the Thespian framework. In the game, I have one ``GameActor`` that initialises 4 ``PlayerActor`` children. Since players are connected to the game over the Internet, the ``PlayerActor`` regularly checks if a player has disconnected and terminates if so.
Lately, most of the games are able to run smoothly until the end and the ``GameActor`` and its children are gracefully finished. But from time to time, the ``PlayerActor`` or ``GameActor`` are forcefully terminated (I do not know the cause of their termination, since nothing appears in the logs).
My problem here is that the forcefully terminated ``PlayerActor`` actors remain as zombie processes and prevent the parent ``GameActor`` actor to terminate as well, thus eating a lot of resources for nothing and leaving the whole system in an **unclean** state.
Is this related to Thespians way of finishing its processes or rather to the underlying linux distribution running the whole architecture?

For information here are my settings:

- Thespian v3.7.0
- Ubuntu 14.04.5
- Python 3.4

If you need any more information, I would gladly provide more details.

Sincerely.

**Comment by kwquick** [comment]
When you say "forcefully termianted", I assume you mean "unexpectedly exit" and that you aren't aware of anything that should be causing them to stop.  Are you using the multiprocTCPBase or a different base?  Even unexpected child exits should cause signals that result in a ChildActorExited message and cleanup of the child, so it's unusual for zombies to be leftover.

There is an internal thespian log, probably written to $TMPDIR, or possibly the current directory, called thespian_system.log.  Can you locate and check that log for unexpected issues, or send that log to me (kq1quick at gmail) if you don't see anything unexpected?  Normally this log should only contain things used for internal debugging of thespian, but it's possible that there is something going on that is not being logged by normal methods.

**Comment by davinellulinvega** [comment]
Hello,

Indeed, by "forcefully terminated", I meant "unexpectedly exit".
For the moment I am using a multiprocTCPBase system.

I have tried to look for a file name thespian_system.log on the server, but could not find any. However, a file thespian.log (and thespian.log.old) is present in the ``/tmp/`` directory. A closer inspection reveals that no error has been written in those logs either. No error message or warnings. Since the code is making an awful lot of request to the actor system, the logs tend to fill in quite quickly (I have already raised the 50Ko limit to 10Mo). So I might have missed any old message.
I will keep an eye out and keep you updated if anything shows.

Sincerely.

**Comment by davinellulinvega** [comment]
Well I guess it is my _lucky_ day. Another batch of ``PlayerActor`` exited unexpectedly and transformed into zombies. But still nothing whether in thespian.log nor in the logs related to my project.

Sincerely.

**Comment by davinellulinvega** [comment]
Just to make sure that I am not doing something stupid that might waste your time: If put a ``return`` statement inside the ``receive_dictMsg`` or ``receive_message`` function, it simply exit the function and ignore any value returned, but does not stop the whole actor?

Sincerely.

**Comment by kwquick** [comment]
You found the right logfile.   The original size is purposely kept very small to avoid causing a lot of overhead, so increasing the size is the right thing.   Unfortunately, it doesn't sound like it is detecting and logging anything unusual.

Exiting the `receiveMessage` at any point is fine: the actor will keep running until it receives an `ActorExitRequest` (which the `receiveMessage` can process before exit), or an external signal.

Are you running into system memory limits or other resource limits that would cause the Out-Of-Memory  (oom) killer to stop your processes?  Are you running under some sort of process manager (e.g. systemd) that might think your service is dead and kill the whole process group?

**Comment by davinellulinvega** [comment]
Hello,

Thank you for the details concerning the ``return`` statement.
Unfortunately, the ``PlayerActor`` process only consumes 0.1% of the 32Go of memory available, so I do not think that an Out-Of-Memory error is the source here. As for your second suggestion, I would have to investigate further, since I am not sure what are the conditions for a process to be considered dead.

In the meantime, I found the possibly related error message in the apache logs:

```
[Tue Mar 28 05:25:02.678431 2017] [:error] [pid 2101] Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
[Tue Mar 28 05:25:02.678451 2017] [:error] [pid 2101] Traceback (most recent call last):
[Tue Mar 28 05:25:02.678456 2017] [:error] [pid 2101]   File "/usr/lib/python3.4/threading.py", line 1288, in _shutdown
[Tue Mar 28 05:25:02.678737 2017] [:error] [pid 2101]     assert tlock is not None
[Tue Mar 28 05:25:02.678744 2017] [:error] [pid 2101] AssertionError:
Exception ignored in: <bound method TCPTransport.__del__ of <thespian.system.transport.TCPTransport.TCPTransport object at 0x6fe590fdb278>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/thespian-3.7.0-py3.4.egg/thespian/system/transport/TCPTransport.py", line 359, in __del__
  File "/usr/local/lib/python3.4/dist-packages/thespian-3.7.0-py3.4.egg/thespian/system/transport/TCPTransport.py", line 342, in close
NameError: name 'hasattr' is not defined
Exception ignored in: <bound method TCPTransport.__del__ of <thespian.system.transport.TCPTransport.TCPTransport object at 0x6fe590fb3278>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/thespian-3.7.0-py3.4.egg/thespian/system/transport/TCPTransport.py", line 359, in __del__
  File "/usr/local/lib/python3.4/dist-packages/thespian-3.7.0-py3.4.egg/thespian/system/transport/TCPTransport.py", line 342, in close
NameError: name 'hasattr' is not defined
```

Since the exception was ignored I am not sure that it is the cause for the zombies, but this is unfortunately the only information I have that could help.

Sincerely.

**Comment by kwquick** [comment]
The error message in the apache logs should not be the cause of your problems, but it's worth keeping an eye on.

The above should normally only occur if you are killing the ActorSystem without calling `ActorSystem().shutdown()` (or if the latter doesn't complete successfully).  The error is that the __del__ for the internal TCP transport module has determined that there was no graceful `close()`, so it's trying to perform a close to release resources like open sockets, but the python environment has already unbound most things, including builtins like `hasattr`.  Arguably the `__del__` shouldn't do this and should allow normal process shutdown to perform those activities, but since it's at the tail end of shutdown, I don't think it is contributing to the unexpected exits or the zombie conditions (although I could be wrong about the latter).

The `thespian.log` has a column like `p2039`, which indicates that the line was generated by the actor process at pid 2039.  I would recommend trying to find the last couple of these lines corresponding to an actor that has unexpectedly exited to see if there are any clues to help us diagnose this.  I'm afraid I don't have many more high-level suggestions here, but I'm happy to keep assisting, and feel free to reach out to me on my direct email (in my previous message) if you prefer.

**Comment by davinellulinvega** [comment]
Hello,

Thank you very much for the precision. Since I have no other clues, I will follow your advice and look into the conditions for a process being forcefully shutdown or becoming a zombie under ubuntu's process manager.
I'll keep you posted if I manage to find anything.

Sincerely.

**Comment by davinellulinvega** [comment]
Hello,

I finally found the source of the error for the mysterious zombies and it seems that I have to apologise for wasting your time. The children ``PlayerActor`` were left behind has zombies, because the parent ``GameActor`` was stuck in an infinite loop. Thus, it never had time to acknowledge the fact that its children were dead and clean after them.
I have fixed the problem of the infinite loop and everything seems to be working correctly now.
So once again sorry and thank you very much for your assistance.

Sincerely.

**Comment by kwquick** [comment]
I'm glad you found the issue, and it was not a waste of time because now we all know what the symptoms and possible cause of this behavior is, which will undoubtably be useful at some future point when it re-occurs for someone else.  Thank you for the update.
