### ISSUE TITLE
Round Robin Troupe Messages

### ISSUE THREAD

**Issue by kevincolyar** [godaddy/Thespian#44]
I have an actor set up in a troupe configuration and each member holds a network connection to a server.  I'm running into an issue where during light loads the same member is used for all messages (every 4s) and this causes the other troupe member's network connection to timeout.

I wonder if it would be possible to do something like round robin the messages to members of the troupe so they don't become stale.  Thoughts?

**Comment by kquick** [comment]
Hi Kevin,

You could definitely experiment with that: change line 96 of
thespian/troupe.py from "self._idle_troupers.append(troupe_member)" to
"self._idle_troupers.insert(0, troupe_member)".

I don't really see any downsides to this approach, so I think this is a
reasonable change to make (if you get a chance to experiment with the
above recommendation, let me know how it goes).

The one caution I would offer is that I would suspect that there are
many other ways you could encounter stale connections to your server, so
you may want to handle this situation anyhow, and also possibly use a
self.wakeupAfter to schedule sends of noop messages as a keepalive.

Regards,
  Kevin


Kevin Colyar writes:

> I have an actor set up in a troupe configuration and each member holds a network connection to a server.  I'm running into an issue where during light loads the same member is used for all messages (every 4s) and this causes the other troupe member's network connection to timeout.
>
> I wonder if it would be possible to do something like round robin the messages to members of the troupe so they don't become stale.  Thoughts?

**Comment by kevincolyar** [comment]
My ideal setup would be to set the `idle_count=1`, that way most of the time my troupe would just contain one actor with one connection, and just spin up additional actors during peaks.

However, I also use my actor system with a simulator for testing and it will send many messages a second to my troupe.  When the `idle_count` is 1, it's continually spawning and killing troupe members, which is opening/closing connections to my server.  It really slows it down.  I assuming it's killing troupe members when they are done processing their message, when it sees that `self.troupe_work_in_progress` is `False`.  Is there some way I could not have them be considered idled so quickly?

**Comment by kwquick** [comment]
Hi @kevincolyar,

Sorry to have not responded to this earlier.  The troupe workers should not be killed if there is active work still available (https://github.com/kquick/Thespian/blob/master/thespian/troupe.py#L90-L95).

I would like to implement the round-robin and delay before killing ideas, so I've created https://github.com/kquick/Thespian/issues/12 which is where the currently active Thespian work is occurring (and thus, I'm closing the issue here).  Please feel free to watch that issue if you are still interested in this functionality.
