### ISSUE TITLE
How do I use actor supervisor with Thespian?

### ISSUE THREAD

**Issue by felipegutierrez** [godaddy/Thespian#47]
Hi,

I wonder how do I create an actor supervisor strategy with Thespian library? I want to create some actors dynamically and if the operation fails I want to restart the actor, and of course, there will be a threshold to restart the actor.

Kind Regards,
Felipe

**Comment by kquick** [comment]
Hi Felipe,

I think you probably saw the answer on the Thespian email reflector list, but essentially any child actor that exits will send a ChildActorExited message to the parent; the parent can detect this message and start a replacement actor if it chooses, or take any other action it thinks is appropriate.

You can also use the thespian troupe if you want identical actors automatically started and stopped on a load-based need scenario.  The troupe internally provides the supervisor strategy along with load scaling.

Also, please be aware that the https://github.com/kquick/Thespian repo tends to be more active than this GoDaddy repo and the former may be a better place for issues (and the email reflector is a great place as well).

-Kevin

**Comment by felipegutierrez** [comment]
ok Kevin,
I saw your answer on the forum. thank you.

I implemented a basic approach and described there. When you have time could you please give your opinion in where I could implement better?

Kind Regards, Felipe
