### ISSUE TITLE
Thespian Connecting To MongoDb

### ISSUE THREAD

**Issue by R2D2-fwks** [godaddy/Thespian#49]
Here is what i am trying to do 
1. Actor System multiprocTCPBase
2. Top level Root Creates two Actors
     2.1 Coordinating Node
     2.2  Pinger Node
3. Coordinating Node queries mongodb 

Also When i change to the default system base class , it starts to work.
In here i am getting the error

Top Level Root
`class RootNode(Actor):
      def receiveMessage( self , msg , sender ):
            print("Initiate")
            if (msg == "start"):
                  print("Message recieved from the actor System")
                  pingerNode = self.createActor(Pinger)
                  coordinatingNode = self.createActor(Cord)
                  pingerStartMessgae = (sender , "StartPingingToDatabase")
                  cordinatingStartMessage = "Initiate"
                  self.send(pingerNode , pingerStartMessgae)
                  self.send(coordinatingNode , cordinatingStartMessage)`

Coordinating Node

       `class Cord(Actor):
           def __init__( self ):
                  self.db = database()

      def receiveMessage( self , msg , sender ):
            if (msg == "Initiate"):
                  self.getProfileOfNode()
            elif (msg == "Got SomeThing to Proces"):
                  self.checkTheDataBasetoFindSomeWork(sender)

      def getProfileOfNode( self ):
            profileData = self.db.getProfileInfo()
            print(profileData)
            NoOfWorkers = profileData[ "noOfworkers" ]
            pingTimeOfWorker = profileData[ "pingTimeofWorkers" ]
            messageSentToEveryWorker = { "message": "Start" , "interval": pingTimeOfWorker }
            print("Send to Create Pool Of actors")
            self.createPoolOfActors(NoOfWorkers , messageSentToEveryWorker)`

Mongodb client

     `class Database:
            def __init__( self ):
                    client = MongoClient(connect=False , host="localhost" ,
                                 port=27017 ,
                                 socketTimeoutMS=100000000 ,
                                 connectTimeoutMS=40000 ,
                                 serverSelectionTimeoutMS=20000 ,
                                 appname="MyAppthespian")
               self.db = client["node"] # node is the database name

         def insertProfile( self ):
               pass

         def getProfileInfo( self ):
               try:
                    print ("Getting thge profile Info")
                  # nodeprofile is the collection name
                  profileInfo = self.db.nodeprofile.find()[ 0 ]
                  # print(profileInfo)
                  # convertTostring=json.dumps(profileInfo)
                  # #print(convertTostring)
                  return profileInfo
            except ConnectionFailure:
                  print("Server not available")

      def insertActorProfile( self , data ):
            self.db.actorprofile.insert_one(data)

      def findWork( self ):
            data = self.db.fileuploading.find_one({ "status": "uploaded" })
            return data
`
Thespian Logs

`2017-11-02 12:47:45.343477 p22079 I    Actor cordinating.Cord @ ActorAddr-(T|:44730) second exception on message Initiate: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thespian/system/actorManager.py", line 168, in _handleOneMessage
    actor_result = self.actorInst.receiveMessage(copy.deepcopy(msg), envelope.sender)
  File "/home/vinoo/work/practice/python/thespian/cordinating.py", line 9, in receiveMessage
  File "/home/vinoo/work/practice/python/thespian/cordinating.py", line 14, in getProfileOfNode
    self.checkTheDataBasetoFindSomeWork(sender)
  File "/home/vinoo/work/practice/python/thespian/database.py", line 12, in getProfileInfo
    appname="MyAppthespian")
IOError: [Errno 32] Broken pipe`

No error in the mongodb side

**Comment by R2D2-fwks** [comment]
Got it , after scratching my head , solved as the multiple actors were creating diff process., i have to kill all the process.

**Comment by kquick** [comment]
Use the `ActorSystem().shutdown()` method to completely shutdown a multi-process Actor System when you are done using it.  Conversely, a started Actor System will persist and be useful longer term, like a daemon process.

Glad you resolved your issue!

Regards,
  Kevin
